### ISSUE TITLE
Unexpected character '`' when build with UglifyJs

### ISSUE THREAD

**Issue by mydearxym** [doowb/remarkable-mentions#1]
UglifyJS is not friendly with ES6 syntax 

[those syntax](https://github.com/doowb/to-mention-link/blob/master/index.js#L67) will cause build errorr when using  UglifyJs

**Comment by jonschlinkert** [comment]
How is your choice of minifier, configuration and build workflow related to this library?

**Comment by doowb** [comment]
The [uglifyjs documentation](https://github.com/mishoo/UglifyJS2#note) recommends using [uglify-es](https://github.com/mishoo/UglifyJS2/tree/harmony) if you want to ugify es6 syntax.
